name = input("Nachname des Ansprechpartners: ")
job = input("Beruf: ")
anschrift = input("Name des Betriebs (Anschrift): ")
full_name = input("vollständiger Name des Ansprechpartners mit Anrede: ")
street = input("Straße mit Hausnummer: ")
city = input("Postleitzahl mit Stadt: ")
date = input("Stadt, Datum: ")
gender = input("Geschlecht des Ansprechpartners (m/f): ").lower()
is_man = gender == "m"
start = input("Startdatum des Praktikums: ")
end = input("Enddatum des Praktikums: ")
category = input("Berufsbereich: ")
print("")
print("")
print("")
print(anschrift)
print(full_name)
print(street)
print(city)
print("")
print(date)
print("")
print("Bewerbung um einen Praktikumsplatz zum " + job)
print("")
if is_man: 
    print("Sehr geehrter Herr " + name + ",")
else:
    print("Sehr geehrte Frau " + name + ",")
print("")
print("durch die Jobbörse habe ich erfahren, dass Sie noch einen Ausbildungsplatz zum " + job + " zu besetzen haben. Hiermit bewerbe ich mich um einen Praktikumsplatz im Zeitraum vom " + start + " bis " + end +". Ich erhoffe mir dadurch den Beruf besser kennen zu lernen und herauszufinden, ob er meinen Vorstellungen entspricht. ")
print("")
print("Ich kann mir meine berufliche Zukunft im Bereich " + category + " durchaus vorstellen.")
print("")
print("Außerdem verfüge ich über einen Realschulabschluss, den ich an der Wiesentalschule in Maulburg 2024 erwarb.")
print("")
print("Zurzeit bin ich in der Berufsvorbereitung beim Internationalen Bund in Lörrach, mit dem Ziel, einen geeigneten Ausbildungsplatz zu finden. Im Rahmen der Berufsvorbereitung möchte ich durch das Praktikum Berufserfahrung sammeln und mir den Beruf " + job + " genauer anschauen.")
print("")
print("Auf eine Einladung zu einem Vorstellungsgespräch würde ich mich sehr freuen.")
print("")
print("Mit freundlichen Grüßen")
print("")
print("")
print("Jannis Steimle")
print("")
print("")
print("")
input("beliebige Taste drücken um das Programm zu beenden.")
